import React from 'react';
import { Card, Typography, List, Space, Tag } from 'antd';
import { BulbOutlined, CheckCircleOutlined } from '@ant-design/icons';
import type { CurrentJob } from '../../types';

const { Title, Text, Paragraph } = Typography;

interface AISuggestionsCardProps {
  job: CurrentJob;
}

export const AISuggestionsCard: React.FC<AISuggestionsCardProps> = ({ job }) => {
  const formatSuggestion = (step: any): string => {
    let suggestion = step.step || 'No step description';

    // Check for valid delta_c (not NaN, not undefined, not 0)
    if (step.delta_c !== undefined && !isNaN(step.delta_c) && Math.abs(step.delta_c) > 0.1) {
      const direction = step.delta_c > 0 ? 'increase' : 'decrease';
      suggestion += ` (${direction} by ${Math.abs(step.delta_c).toFixed(1)}°C)`;
    }

    // Check for valid delta_mpm (not NaN, not undefined, not 0)
    if (step.delta_mpm !== undefined && !isNaN(step.delta_mpm) && Math.abs(step.delta_mpm) > 0.1) {
      const direction = step.delta_mpm > 0 ? 'increase' : 'decrease';
      suggestion += ` (${direction} by ${Math.abs(step.delta_mpm).toFixed(1)} m/min)`;
    }

    return suggestion;
  };

  return (
    <Card
      bordered={false}
      style={{
        height: '100%',
        background: 'linear-gradient(135deg, #2563eb 0%, #7c3aed 100%)',
        boxShadow: '0 4px 12px rgba(37, 99, 235, 0.25)'
      }}
    >
      <Space direction="vertical" size={16} style={{ width: '100%' }}>
        <div style={{ textAlign: 'center' }}>
          <BulbOutlined style={{ fontSize: 40, color: '#fff', marginBottom: 12 }} />
          <Title level={4} style={{ margin: 0, color: '#fff' }}>
            AI Suggestions
          </Title>
          <Text style={{ fontSize: 12, color: 'rgba(255,255,255,0.85)' }}>
            Minimize Waste with AI Insights
          </Text>
        </div>

        <div style={{
          padding: 16,
          background: 'rgba(255, 255, 255, 0.15)',
          borderRadius: 8,
          backdropFilter: 'blur(10px)'
        }}>
          <Space direction="vertical" size={8} style={{ width: '100%' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
              <Text strong style={{ color: '#fff', fontSize: 13 }}>
                Recommendation
              </Text>
              <Tag
                color={job.actionConfidence > 0.8 ? 'success' : job.actionConfidence > 0.6 ? 'warning' : 'default'}
                style={{ margin: 0 }}
              >
                {(job.actionConfidence * 100).toFixed(0)}% Confidence
              </Tag>
            </div>
            <Paragraph style={{ color: 'rgba(255,255,255,0.95)', margin: 0, fontSize: 12 }}>
              {job.actionTitle}
            </Paragraph>
          </Space>
        </div>

        {job.actionSteps && job.actionSteps.length > 0 && (
          <div style={{
            padding: 16,
            background: 'rgba(255, 255, 255, 0.95)',
            borderRadius: 8,
            maxHeight: 300,
            overflowY: 'auto'
          }}>
            <Text strong style={{ fontSize: 13, display: 'block', marginBottom: 12, color: '#1f1f1f' }}>
              Action Steps:
            </Text>
            <List
              size="small"
              dataSource={job.actionSteps}
              renderItem={(step) => (
                <List.Item style={{ padding: '8px 0', border: 'none' }}>
                  <Space align="start" size={8}>
                    <CheckCircleOutlined style={{ color: '#52c41a', fontSize: 16, marginTop: 2 }} />
                    <div>
                      <Text style={{ fontSize: 12, color: '#1f1f1f' }}>
                        {formatSuggestion(step)}
                      </Text>
                    </div>
                  </Space>
                </List.Item>
              )}
            />
          </div>
        )}

        <div style={{
          padding: 12,
          background: 'rgba(255, 255, 255, 0.1)',
          borderRadius: 6,
          textAlign: 'center'
        }}>
          <Text style={{ fontSize: 11, color: 'rgba(255,255,255,0.85)' }}>
            These recommendations are generated by our AI model to optimize production and reduce waste
          </Text>
        </div>
      </Space>
    </Card>
  );
};
